### ISSUE TITLE
有个地方注释有点问题。

### ISSUE THREAD

**Issue by minghongss** [lovelyyoshino/FAST_LIO2_Noted#2]
use-ikfom.hpp，line 42。我认为这个矩阵的的注释应该是：pos(3), rot(3),offset_R_L_I(3),offset_T_L_I(3), vel(3), bg(3), ba(3), grav(3)。刚好可以和论文的公式（1）对上。你可能是从49-51行得出的注释。按你的注释，后面好几处地方都解释不通。

**Comment by lovelyyoshino** [comment]
这一块我也有所怀疑，但是那除非说49-51行写的有问题。但是df_dx也可以侧面证明公式吧。您可以push一下您的看法，一起讨论一下
